name: CI

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "*"

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - goarch: amd64
          - goarch: amd64
            testflags: "-race"
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
      - name: Test all
        run: go test ${{matrix.testflags}} ./...
        env:
          GOARCH: ${{ matrix.goarch }}
  apidiff:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
      - name: Run api-diff
        uses: joelanford/go-apidiff@main
